## Synthetic population pipeline for Munich
## based on the synpp package

run_synthesis: true

# This is the path to a directory where the pipeline can store temporary data
data_path: ../../data/city_specific/munich/
working_directory: ../../data/city_specific/munich/cache

# This section defines which parts of the pipeline should be run
# if run_synthesis:
run:
  - synthesis.output
# else: 
#   run:
#     - matsim.output

# Here the configuraiton of the pipeline starts
config:
  # Some general configuration
  processes: 1

  # Define whether to use ENTD or EGT as the household travel survey (HTS)
  hts: entd

  # Define sampling rate and random seed for the output population
  sampling_rate: 0.001
  random_seed: 1234
 
  # Paths to the input data and where the output should be stored
  data_path: ../../data/city_specific/munich/data
  output_path: ../../data/city_specific/munich/output
  output_prefix: munich_
  osm_path_bavaria: munich/data/osm/bayern-latest.osm.pbf 

  if not run_synthesis: 
    osmosis_binary: /opt/homebrew/bin/osmosis
    osmconvert_binary: munich/data/osm/osmconvert

  # Only interesting if you run the simulation
  java_memory: 12G

  # Defaults for Munich
  home_location_sampling: weighted
  mode_choice: false
  matching_attributes: ["sex", "age_class", "has_license"]

  if not run_synthesis:
    gtfs_path: gtfs
    osm_path: osm

# Overrides for the Munich pipeline compared to the ÃŽle-de-France pipeline
aliases:
  data.census.filtered: munich.ipf.attributed
  synthesis.population.income.selected: munich.income
  synthesis.population.spatial.home.zones: munich.homes
  synthesis.locations.home.locations: munich.locations.home
  synthesis.locations.education: munich.locations.education
  synthesis.locations.secondary: munich.locations.secondary
  synthesis.locations.work: munich.locations.work
  data.od.weighted: munich.gravity.model
  data.spatial.iris: munich.data.spatial.iris
  data.spatial.codes: munich.entd_codes
  synthesis.population.spatial.primary.locations: munich.locations.synthesis.replacement
  synthesis.population.enriched: munich.synthesis.population.enriched
  matsim.simulation.prepare: munich.matsim.simulation.prepare

